### ISSUE TITLE
Needs protection against too long records

### ISSUE THREAD

**Issue by pkoppenb** [efranzin/python#1]
Hi @efranzin ,

First I wanted to thank you for providing an example that got me started with the inspirehep api. The script generating my publication list was broken by a change of database in LHCb. Rather than understanding the new api I reverted to inspire. The result is [here](https://www.nikhef.nl/~pkoppenb/papers.html). 

Since I have you attention I'd like to report that your script breaks in my case. My publication list is just too long for the inspire api. I had to break in chunks by year (which is fine, I only need to update the last bit anyway). You probably want to add a `try: except`: around lines 74-75. inspirehep just replies `<Response [502]>` if I don't specify a year but the error appears in `json`, which is not helpful for the user.

Patrick

**Comment by efranzin** [comment]
Hi Patrick/@pkoppenb,

Thanks for pointing this out. I must say that I have never tested my script for authors who are part of a large collaboration.
Lately I have been implementing a few things but I have not commited it yet. I will try to take care of this issue as well.

Thanks again,
Edgardo

**Comment by efranzin** [comment]
Hi @pkoppenb,

the issue is solved. Now the data are splitted into "pages" to avoid the bad gateway server error. I have tested with your profile as well as other people in large collaboration and it works (it could take some time tho). Thanks again and let me know whether you find any other issues.

Best,
Edgardo
